bb = User.create(username: "BingoBongo", password: "abc123")

lima = City.create(name: "Lima", state: "Lima", country: "Peru", continent: "South America", image_key: "9VTHnaNzib-1zgdzaoLO7Q", flag_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Flag_of_Peru_%28state%29.svg", food: "My favorite meal is Ceviche. Goes so well with a glass of Chicha Morada!", language: "My friends and I all speak Spanish! ¡Bienvenidos a nuestro país!", religion: "I go with my family to Catholic mass on Sundays!")
toronto = City.create(name: "Toronto", state: "Ontario", country: "Canada", continent: "North America", image_key: "rY7guF8KWnRuQ-GDKxuPTw", flag_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1200px-Flag_of_Canada_%28Pantone%29.svg.png", food: "You should try a peameal bacon sandwich. I think you can get one down at the St. Lawrence Market, eh?", language: "Many people in other parts of the country speak French, and a few here do as well. But we primarily speak English here.", religion: "People here practice all kinds of religions, but most seem to be Catholics, Protestants, or not very religious.")
tokyo = City.create(name: "Tokyo", state: "", country: "Japan", continent: "Asia", image_key: "IlFyfyTOvBxFrskJKyOZ6Q", flag_url: "https://cdn11.bigcommerce.com/s-ey7tq/images/stencil/1280x1280/products/3342/18816/japan-flag__36690.1575327806.jpg?c=2", food: "You've never had sushi like we have here!", language: "We speak Japanese here. おはようございます！")
macau = City.create(name: "Macao", state: "Macao", country: "People's Republic of China", continent: "Asia", image_key: "KGHbNmfZQ8z9BcWb1a_3lg", flag_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/1200px-Flag_of_Macau.svg.png", food: "Oh man, I love a good Portguese Egg Tart! 吃飯囉！", language: "Though many people here speak Portuguese, my family and I speak in Chinese!", religion: "Many people here are Buddhists, and there are a few Catholics, but I don't practice any religion.")
# City.create(name: "", state: "", country: "India", continent: "Asia", image_key: "rwyMGYLiJIeHA1vQVdbzIg", flag_url: "", food: "", language: "")
# City.create(name: "Zürich", state: "", country: "", continent: "Europe", image_key: "XPJZd38HsQTpdHPIFD0CHg", flag_url: "", food: "", language: "")
rome = City.create(name: "Rome", state: "Lazio", country: "Italy", continent: "Europe", image_key: "S42Qzdt2b6Zw0iSs6imTXw", flag_url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/1200px-Flag_of_Italy.svg.png", food: "My grandmother's gnocchi is just so good, you have to try!! Mangia!", language: "We speak Italian here.")
# City.create(name: "Paris", state: "", country: "", continent: "Europe", image_key: "pVbOKwcGeh0hc3mYR7cQvg", flag_url: "", food: "", language: "")
nyc= City.create(name: "New York City", state: "New York", country: "United States", continent: "North America", image_key: "yoqbCIEHbWB16feLHU0saA", flag_url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1200px-Flag_of_the_United_States.svg.png", food: "You thought you knew what good pizza was until you had some of this! Grab a bagel while you're at it.", language: "People in this city speak all kinds of languages! But the most common, in the city and the country, is definitely English.")
# City.create(name: "Pueblo", state: "", country: "", continent: "North America", image_key: "Ml86dTM9LPynllM9pDl7ty", flag_url: "", food: "", language: "")
# City.create(name: "Buenos Aires", state: "", country: "Argentina", continent: "South America", image_key: "vVtXCecu0MWJV5tC7qyJYQ", flag_url: "", food: "", language: "")
sp = City.create(name: "São Paulo", state: "São Paulo", country: "Brazil", continent: "South America", image_key: "5xpLICrGF5E0T9628G5xul", flag_url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1200px-Flag_of_Brazil.svg.png", food: "You've got to try a Pao de Queijo, maybe with a cafe con leche. Delicioso!", language: "We speak Portuguese here.")

# cf = City.create(name: "Cienfuegos", state: "Cienfuegos", country: "Cuba", flag_url: "https://cdn.britannica.com/10/5110-004-38075E57/Flag-Cuba.jpg", food: "maduros", language: "Spanish")

bb.passport.trips.create(city: lima, date_travelled: "Tuesday March 9th 2021")
bb.passport.trips.create(city: sp, date_travelled: "Monday November 7th 2018")